/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t X_png[];
extern const uint8_t X_png_end[];
#if __cplusplus >= 201103L
static constexpr size_t X_png_size=10948;
#else
static const size_t X_png_size=10948;
#endif
