/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t placeMarkP2_wav[];
extern const uint8_t placeMarkP2_wav_end[];
#if __cplusplus >= 201103L
static constexpr size_t placeMarkP2_wav_size=4764;
#else
static const size_t placeMarkP2_wav_size=4764;
#endif
