/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t placeMark_wav[];
extern const uint8_t placeMark_wav_end[];
#if __cplusplus >= 201103L
static constexpr size_t placeMark_wav_size=8250;
#else
static const size_t placeMark_wav_size=8250;
#endif
