/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _placeMarkP2_h_
#define _placeMarkP2_h_
//---------------------------------------------------------------------------------
extern const unsigned char placeMarkP2[];
extern const int placeMarkP2_size;
//---------------------------------------------------------------------------------
#endif //_placeMarkP2_h_
//---------------------------------------------------------------------------------
