/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _placeMarkP1_h_
#define _placeMarkP1_h_
//---------------------------------------------------------------------------------
extern const unsigned char placeMarkP1[];
extern const int placeMarkP1_size;
//---------------------------------------------------------------------------------
#endif //_placeMarkP1_h_
//---------------------------------------------------------------------------------
