/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t numbers_0to4_png[];
extern const uint8_t numbers_0to4_png_end[];
#if __cplusplus >= 201103L
static constexpr size_t numbers_0to4_png_size=43887;
#else
static const size_t numbers_0to4_png_size=43887;
#endif
