/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t O_png[];
extern const uint8_t O_png_end[];
#if __cplusplus >= 201103L
static constexpr size_t O_png_size=8674;
#else
static const size_t O_png_size=8674;
#endif
