/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t p2Cursor_png[];
extern const uint8_t p2Cursor_png_end[];
#if __cplusplus >= 201103L
static constexpr size_t p2Cursor_png_size=6539;
#else
static const size_t p2Cursor_png_size=6539;
#endif
