/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t grid_png[];
extern const uint8_t grid_png_end[];
#if __cplusplus >= 201103L
static constexpr size_t grid_png_size=2420;
#else
static const size_t grid_png_size=2420;
#endif
